#!/sbin/busybox sh

export BOOTREC_CACHE_NODE="/dev/block/mmcblk0p11 b 179 11"
export BOOTREC_CACHE="/dev/block/mmcblk0p11"
export BOOTREC_EVENT_NODE="/dev/input/event2 c 13 66"
export BOOTREC_EVENT="/dev/input/event2"
export BOOTREC_CONTROL_LED="/sys/class/led/fih_led/control"
