#!/sbin/busybox sh

export BOOTREC_CACHE_NODE="/dev/block/mmcblk0p11 b 179 11"
export BOOTREC_CACHE="/dev/block/mmcblk0p11"
export BOOTREC_EVENT_NODE="/dev/input/event0 c 13 64"
export BOOTREC_EVENT="/dev/input/event0"
export BOOTREC_LED_RED="/sys/class/leds/red/brightness"
export BOOTREC_LED_GREEN="/sys/class/leds/green/brightness"
export BOOTREC_LED_BLUE="/sys/class/leds/blue/brightness"
